import '#/styles/style.scss';
import '#/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Analytics } from '#/components/analytics';
import { TailwindIndicator } from '#/components/tailwind-indicator';
import { ThemeProvider } from '#/components/theme-provider';
import LayoutWrapper from '#/components/ui/layout';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body className={inter.className}>
   <ThemeProvider attribute="class" defaultTheme="system" enableSystem>  
          <LayoutWrapper>
        {children}
        </LayoutWrapper>
     <Analytics />
      <TailwindIndicator />
      </ThemeProvider>
      </body>

    </html>
  )
}
